use ShopOnline_Demo
go
insert into BaiViet (maBV , tenBV , hinhDD , ngayDang , ndTomTat , taiKhoan , loaiTin , daDuyet , noiDung)
        values('BV01' , N'Ưu điểm của chip Intel Tiger Lake' , '\images\BaiViet\bv01.jpg' ,
                '2021/12/4' , N'Chip Intel Tiger Lake có tốc độ xử lý nhanh, kết nối mạng ổn định, tiết kiệm năng lượng, đáp ứng nhu cầu học tập và giải trí trên laptop.' ,
                'minh' , 'TT' , 1 , N'Intel Tiger Lake là thế hệ chip thứ 11 của Intel gồm 3 dòng Core i3, i5 và i7, được sản xuất trên quy trình 10nm SuperFi với nhiều cải tiến về bộ nhớ đệm, nâng tầm hiệu năng và cải thiện tuổi thọ pin. Ra mắt vào cuối năm 2020, dòng chip này tạo sự đột phá về công nghệ, giúp những chiếc laptop mỏng nhẹ cũng có thể "cân" được nhiều tác vụ.
Điểm khác biệt lớn giữa Tiger Lake và phiên bản tiền nhiệm là bộ xử lý hiệu suất được nâng lên gấp 2,7 lần mà không tăng công suất tiêu thụ năng lượng và nhiệt độ tỏa ra khi vận hành. Bên cạnh đó, Tiger Lake còn tích hợp nhiều card đồ họa mạnh, giúp người dùng tận hưởng các tựa game eSport hay AAA hạng nặng một cách mượt mà. Cùng với đó là chứng nhận Intel Evo đảm bảo cho laptop sử dụng chip Tiger Lake luôn hoạt động tối thiểu 9 tiếng đồng hồ, tùy thuộc vào điều kiện sử dụng.
Dải sản phẩm laptop gaming sở hữu chip Intel Tiger Lake cho phép game thủ trải nghiệm nhiều tựa game hạng nặng, thực hiện đa tác vụ thiết kế đồ họa. Đơn cử như Laptop MSI Katana GF66 11UC i7 (224VN), với chip Intel Core i7 11800H, RAM 8 GB, 512 GB SSD (hỗ trợ thêm một khe M2 mở rộng lên đến một TB). Máy trang bị card đồ họa RTX 3050, có thể "cân" được hiệu ứng ray tracing, giúp cải thiện ánh sáng trong game, không lo bị giật, lag hay xé khung hình.
Mẫu laptop này có màn hình tần số quét lên đến 144 Hz, hạn chế vấn đề nhoè mờ ảnh, mang đến trải nghiệm xem phim và cutscene (cắt cảnh) tốt hơn. Với mức giảm 500.000 đồng, laptop MSI Katana GF66 đang có giá 29,49 triệu đồng kèm ưu đãi tặng chuột Gaming Rapoo V16 khi mua online tại Thế Giới Di Động.
Một đại diện khác thuộc dòng gaming sử dụng chip Intel Tiger Lake là Acer Nitro 5 Gaming AN515 57 74NU i7. Máy có cấu hình ổn định, chip Intel Core i7 dòng H mới nhất, ổ SSD 512 GB tốc độ cao, lưu trữ thoải mái, card rời RTX3050Ti 4GB sẵn sàng chiến các game đỉnh cao và đồ họa ấn tượng.
Không chỉ ghi điểm nhờ hiệu năng, Acer Nitro 5 Gaming còn sử dụng bàn phím đèn nền LED RGB bốn vùng, hỗ trợ người dùng xác định vị trí laptop trong điều kiện thiếu sáng. Giá của máy được giảm một triệu đồng, còn 28,99 triệu đồng, tặng balo gaming Acer, tặng thêm chuột Gaming Rapoo V16 khi mua online.
Bộ xử lý của Tiger Lake còn được tích hợp sẵn card đồ họa Intel Iris Xe, giúp tăng hiệu suất chỉnh sửa hình ảnh, thiết kế 2D, dựng video, nâng khả năng xử lý đồ họa và xuất file nhanh chóng.
Nhờ tích tích hợp Tiger Lake, mẫu laptop Acer Aspire A514 54 53T8 i5 trở thành trợ thủ đắc lực cho dân văn phòng. Máy trang bị vi xử lý Core i5 1135G7, RAM 8 GB giúp xử lý tốt nhiều tác vụ văn phòng, ổ SSD 512 GB giúp khởi động máy chỉ trong 3-4 giây. Cùng với đó là màn hình IPS Full HD 14 inch (1920x1080), cung cấp góc nhìn rộng 178 độ. Tại Thế Giới Di Động, máy được giảm 400.000 đồng, còn 19,59 triệu đồng, tặng kèm chuột không dây khi mua online.
Bên cạnh cấu hình cao, khả năng kết nối và tương tác cũng là điểm nổi bật của chip Intel Tiger Lake. Với Wifi 6 được tích hợp cùng, chip cho tốc độ kết nối tăng hơn 30-40% so với Wifi 5, đảm bảo chất lượng cho các buổi học trực tuyến.
Nhờ đó, các dòng máy sử dụng chip này đáp ứng tốt nhu cầu học tập cơ bản của học sinh, sinh viên. Đơn cử trong số đó là Lenovo Ideapad 5 15ITL05 i5 1135G7, đạt chuẩn Wifi 6 AX201, nâng cao tốc độ kết nối và truyền tải dữ liệu. Máy có vẻ ngoài sang trọng, thiết kế mặt lưng kim loại màu xám, gọn nhẹ, phù hợp cho việc di chuyển liên tục. Máy tích hợp cảm ứng vân tay trên nút nguồn không cần điền mật khẩu. Sản phẩm đang giảm tới 400.000 đồng tại Thế Giới Di Động, từ 20,59 triệu chỉ
còn 20,99 triệu đồng, cùng ưu đãi tặng chuột không dây và chính sách bảo hành 2 năm.')
insert into BaiViet (maBV , tenBV , hinhDD , ngayDang , ndTomTat , taiKhoan , loaiTin , daDuyet , noiDung)
        values('BV02' , N'Card đồ họa "sốt" trở lại' , '\images\BaiViet\bv02.jpg' ,
                '2021/12/4' , N'Giá card đồ họa tăng mạnh sau khi Bitcoin quay lại mốc 50.000 USD, khiến người dùng phổ thông không thể tiếp cận sản phẩm.' ,
                'minh' , 'TT' , 1 , N'Giá Bitcoin đã tăng 4,2% lên gần 50.440 USD trong phiên giao dịch sáng 23/8. Theo Bloomberg, đây là lần gần nhất trong vòng ba tháng Bitcoin lấy lại mốc trên 50.000 USD. Ngoài những người tham gia vào thị trường tiền số, sự kiện này còn ảnh hưởng trực tiếp đến cộng đồng game thủ và người dùng phổ thông.
Li Hua, một game thủ ở Bắc Kinh, bắt đầu theo dõi giá card đồ họa từ tháng 5. Khi đó, anh nghĩ rằng tháng 6 sẽ là thời điểm tốt nhất để mua một card đồ họa mới cho dàn máy tính chơi ở nhà. "Tôi đã chờ đợi, theo dõi trong ba tháng để chờ giá card đồ hoạ về mức bình thường. Bây giờ tôi vẫn chỉ có thể tiếp tục chờ", Hua nói.
Theo Li Hua, loạt card đồ họa RTX30 của Nvidia có giá khá cao trong khoảng từ tháng 3 đến tháng 5. Sau đó, giá các model trong dòng này giảm dần đến đầu tháng 8 và bất ngờ tăng trở lại. Ví dụ, card đồ hoạ Nvidia RTX 3060 ban đầu có giá 2.499 nhân dân tệ (8,7 triệu đồng), sau đó được đẩy lên 7.499 nhân dân tệ (26,3 triệu đồng). Bước sang tháng 7, model này giảm đáng kể xuống còn dưới 4.000 nhân dân tệ (14 triệu đồng) nhưng vẫn ế ẩm. Những người dùng như Li Hua tiếp tục chờ giá sản phẩm về đúng giá trị. Các thợ đào cũng không mấy bận tâm vì thị trường tiền số ảm đạm.
Tuy nhiên, mọi thứ thay đổi khi giá Bitcoin "ấm lên" từ cuối tháng 7. Mẫu card Nvidia RTX 3080 đột ngột tăng giá 52% từ 9.599 nhân dân tệ (33,7 triệu đồng) ngày 31/7 lên 14.599 nhân dân tệ (51,3 triệu đồng) vào sáng 1/8. Khi đó, những người bán hàng trên JD.com nhận không ít chỉ trích vì mức giá bị coi là điên rồ, vô lý. Nhưng khi Bitcoin cán mốc 50.000 USD vào 23/8, trên một số chợ trực tuyến Trung Quốc, card đồ hoạ lại cháy hàng và người dùng khó tìm mua các mẫu card từ phổ thông đến cao cấp.
Pan Helin, Giáo sư của Viện Kinh tế Kỹ thuật số thuộc Đại học Kinh tế và Luật Trung Nam (Trung Quốc), cho rằng việc giá card đồ hoạ tăng bất thường có thể đến từ nhiều yếu tố, trong đó có việc thiếu hụt chip trên toàn cầu.
"Nhưng nguyên nhân chủ yếu là Bitcoin và các tiền điện tử khác tăng giá khiến lợi nhuận của việc khai thác được đẩy cao, nhiều thợ đào thu gom card đồ hoạ, các cửa hàng tranh thủ bán kiếm lời", Helin phân tích.
Những người không tham gia vào việc khai thác tiền điện tử như Li Hua cho biết họ không lạ với việc giá card "nhảy múa" theo giá Bitcoin. Nhưng ngay cả khi tiền điện tử đi xuống hồi tháng 5, cộng đồng game thủ và người dùng phổ thông vẫn không thể mua được card đồ hoạ với giá hợp lý. Sau khi hoạt động khai thác tiền điện tử tại Trung Quốc bị cấm, một số lượng lớn card đồ họa cũ dòng Nvidia RTX30 đã xuất hiện trên các nền tảng mua sắm. Nhiều người bán thẳng thắn cho biết đây là card thải ra từ các trang trại đào Bitcoin, nhưng vẫn đắt so với giá trị gốc.
Một thợ đào tiền số lâu năm cho biết, những chiếc card đồ họa cũ này đã hoạt động hết công suất trong một thời gian dài. Tản nhiệt không đủ có thể dễ gây hỏng chip và ảnh hưởng hiệu suất.
"Rõ ràng, vẫn có lượng người dùng lớn chưa thể tiếp cận card đồ hoạ do giá bị đẩy lên quá cao. Ngay cả nguồn cung chip bị ảnh hưởng hay tác động của dịch bệnh, thị trường cung cầu vẫn có thể cân bằng nếu không có tác động của hoạt động khai thác tiền số", Pan Helin nói.
Wang Peng, trợ lý giáo sư tại Đại học Renmin (Trung Quốc), nhận định: "Với thị trường hiện tại, card đồ hoạ đã trở thành mục tiêu của các đối tượng đầu cơ kiếm lời. Khác với sự biến động của tiền số, card đồ hoạ là thiết bị phần cứng, dễ bị ảnh hưởng bởi các yếu tố về tuổi thọ, hiệu suất. Vì vậy, việc định giá tương
ứng với sự lên xuống của Bitcoin, Ethereum là vô lý".')
insert into BaiViet (maBV , tenBV , hinhDD , ngayDang , ndTomTat , taiKhoan , loaiTin , daDuyet , noiDung)
        values('BV03' , N'Card đồ họa giảm giá' , '\images\BaiViet\bv03.jpg',
                '2021/12/4' , N'Nhiều mẫu card đồ họa tại Việt Nam bắt đầu giảm giá, cho phép người dùng mua lẻ thay vì phải mua kiểu "bia kèm lạc" như trước đây.' , 
                'minh' , 'TT' , 1 , N'Tại nhiều cửa hàng bán thiết bị vi tính, chính sách "chỉ bán card đồ họa khi mua kèm bộ máy tính" bắt đầu được bỏ từ đầu tuần này. Việc "cởi trói" bắt đầu áp dụng cho một số mẫu có nhiều hàng, như GT 1030, GTX 1660/1660 Ti, RX 6700 XT/6800 XT/ 6900 XT...
"Tôi đã phải chờ gần hai tháng, cuối cùng đã mua được card đồ họa ưng ý", Nguyễn Đại, một người làm trong lĩnh vực đồ họa tại Hà Nội, chia sẻ trên nhóm mua bán linh kiện. Đại cho biết, mẫu VGA mà anh mua để nâng cấp máy tính là GTX 1660 6GB. Sản phẩm vốn có giá khoảng 13 triệu đồng, nhưng từ dạo đầu năm, các cửa hàng bán chênh 3 triệu đồng nếu người dùng mua lẻ, nếu không buộc phải mua trọn bộ máy tính. Trên thị trường "chợ đen", sản phẩm này cũng được rao bán với giá không dưới 15 triệu đồng.
"Mình đã có bộ máy tính, chỉ cần nâng cấp card đồ họa nên chấp nhận chờ đợi. May mắn là chỉ phải chờ ít tháng", Đại nói. Thực tế, nhiều người phải chờ hơn nửa năm vì thị trường card đồ họa biến động mạnh suốt thời gian qua.
"Ban đầu sẽ là bỏ chính sách mua kèm bộ máy, đồng thời giảm giá nhẹ nhẹ một số sản phẩm. Sắp tới, có thể card đồ họa sẽ giảm giá mạnh", Đức Tiến, Giám đốc sản phẩm một hệ thống bán đồ vi tính tại Thái Hà (Hà Nội) chia sẻ.
Theo anh Tiến, thị trường card đồ họa tại Việt Nam đang có biến động lớn, do ảnh hưởng từ tình hình giảm giá trên thị trường tiền điện tử, cũng như việc các "nông trại đào coin" phải rời khỏi Trung Quốc. Điều này khiến một lượng VGA lớn được "xả" ra thị trường, khiến hàng mới phải điều chỉnh theo.
Đại diện một nhà phân phối thiết bị vi tính lớn tại Việt Nam cho biết, thị trường card đang trở lại theo hướng có lợi cho người dùng. "Sắp tới, card đồ họa sẽ dễ mua hơn, và một số mẫu có thể sẽ giảm giá", anh nói. Tuy nhiên, người này cũng cho biết hiện tại thị trường vẫn đang trong trạng thái khan hàng, do lượng hàng từ nhà sản xuất về Việt Nam chưa đủ so với nhu cầu. Vì vậy, giá chưa thể giảm ngay.
Nhiều hệ thống bán lẻ thiết bị vi tính cũng ghi nhận doanh số từ card đồ họa tăng nhẹ thời gian gần đây. Chủ một cửa hàng máy tính tại đường Lê Thanh Nghị (Hà Nội) cho biết, người dùng hiện vẫn "dè dặt" khi mua card đồ họa, do giá còn cao và chờ đợi tiền điện tử giảm giá để mua hàng thanh lý giá tốt.
So với tháng 6/2020, hầu hết card đồ họa đều tăng vài triệu đến hàng chục triệu đồng. Nhiều mẫu tăng giá gấp đôi vì cơn sốt đào tiền điện tử, cũng như ảnh hưởng từ khủng hoảng chip toàn cầu. Theo một số nhà sản xuất,
có thể đến năm 2022, khi nguồn cung dồi dào trở lại, linh kiện máy tính mới giảm giá.')